name: gxi-thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - expat=2.7.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcxx=21.1.8
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - liblapack=3.11.0
  - libllvm21=21.1.8
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.51.2
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm=21.1.8
  - llvm-openmp=21.1.8
  - llvmlite=0.46.0
  - ncurses=6.5
  - numba=0.63.1
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.19
  - python_abi=3.10
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.51.2
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - captum==0.8.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - colour==0.1.5
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - galois==0.4.10
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shapiq==1.4.1
      - six==1.17.0
      - sparse-transform==0.2.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - torch==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - transformers==4.57.6
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3

